import { Homeowner, Profile, ActivityLog } from "@/types/database";

export const MOCK_PROFILES: Profile[] = [
  {
    id: "user-super-admin-01",
    full_name: "Atty. Renato Ramos (HOA President)",
    email: "president@stjosephvillage6.ph",
    role: "super_admin",
    status: "Active",
    created_at: "2026-01-01T08:00:00Z",
    permissions: {
      can_create_homeowner: true,
      can_edit_homeowner: true,
      can_delete_homeowner: true,
      can_view_homeowner: true,
      can_export_excel: true,
      can_manage_users: true,
      can_grant_permissions: true,
      can_view_dashboard_stats: true,
    },
  },
  {
    id: "user-admin-02",
    full_name: "Engr. Marilou Cruz (HOA Vice President)",
    email: "vp.cruz@stjosephvillage6.ph",
    role: "admin",
    status: "Active",
    created_at: "2026-01-05T09:30:00Z",
    permissions: {
      can_create_homeowner: true,
      can_edit_homeowner: true,
      can_delete_homeowner: false,
      can_view_homeowner: true,
      can_export_excel: true,
      can_manage_users: false,
      can_grant_permissions: false,
      can_view_dashboard_stats: true,
    },
  },
  {
    id: "user-staff-03",
    full_name: "Carla Mae Dizon (HOA Secretary)",
    email: "carla.dizon@stjosephvillage6.ph",
    role: "user",
    status: "Active",
    created_at: "2026-01-15T10:15:00Z",
    permissions: {
      can_create_homeowner: true,
      can_edit_homeowner: false,
      can_delete_homeowner: false,
      can_view_homeowner: true,
      can_export_excel: false,
      can_manage_users: false,
      can_grant_permissions: false,
      can_view_dashboard_stats: true,
    },
  },
  {
    id: "user-staff-04",
    full_name: "Juanito 'Jun' Santos (Volunteer Staff)",
    email: "jun.santos@stjosephvillage6.ph",
    role: "user",
    status: "Inactive",
    created_at: "2026-02-01T11:00:00Z",
    permissions: {
      can_create_homeowner: false,
      can_edit_homeowner: false,
      can_delete_homeowner: false,
      can_view_homeowner: true,
      can_export_excel: false,
      can_manage_users: false,
      can_grant_permissions: false,
      can_view_dashboard_stats: false,
    },
  },
];

export const MOCK_HOMEOWNERS: Homeowner[] = [
  {
    id: "ho-0001",
    full_name: "Eduardo M. Santos",
    ownership_type: "Owner",
    gender: "Male",
    birthdate: "1975-04-12",
    age: 51,
    address: "Block 12 Lot 8, St. Joseph Village 6 Phase 4",
    household_count: 4,
    contact_mobile: "0917-123-4567",
    contact_email: "eduardo.santos@example.com",
    pet_count: 2,
    ga_proxy_name: "Maria Teresa Santos",
    ga_proxy_relationship: "Spouse",
    status: "Active",
    created_at: "2026-01-10T14:20:00Z",
    household_members: [
      { id: "hm-101", homeowner_id: "ho-0001", member_name: "Maria Teresa Santos", relationship: "Spouse" },
      { id: "hm-102", homeowner_id: "ho-0001", member_name: "Kevin James Santos", relationship: "Son" },
      { id: "hm-103", homeowner_id: "ho-0001", member_name: "Alyssa Marie Santos", relationship: "Daughter" },
    ],
  },
  {
    id: "ho-0002",
    full_name: "Corazon V. Reyes",
    ownership_type: "Owner",
    gender: "Female",
    birthdate: "1968-11-23",
    age: 57,
    address: "Block 7 Lot 15, St. Joseph Village 6 Phase 4",
    household_count: 3,
    contact_mobile: "0920-987-6543",
    contact_email: "cory.reyes@example.com",
    pet_count: 1,
    ga_proxy_name: "Jonathan Reyes",
    ga_proxy_relationship: "Son",
    status: "Active",
    created_at: "2026-01-12T09:15:00Z",
    household_members: [
      { id: "hm-201", homeowner_id: "ho-0002", member_name: "Jonathan Reyes", relationship: "Son" },
      { id: "hm-202", homeowner_id: "ho-0002", member_name: "Lourdes Villanueva", relationship: "Mother" },
    ],
  },
  {
    id: "ho-0003",
    full_name: "Rafael James D. De Guzman",
    ownership_type: "Renter",
    gender: "Male",
    birthdate: "1988-08-15",
    age: 38,
    address: "Block 19 Lot 4, St. Joseph Village 6 Phase 4",
    household_count: 2,
    contact_mobile: "0918-555-1234",
    contact_email: "rj.deguzman@example.com",
    pet_count: 0,
    ga_proxy_name: "",
    ga_proxy_relationship: "",
    status: "Active",
    created_at: "2026-01-20T11:45:00Z",
    household_members: [
      { id: "hm-301", homeowner_id: "ho-0003", member_name: "Patricia Anne Lim", relationship: "Partner" },
    ],
  },
  {
    id: "ho-0004",
    full_name: "Dr. Elizabeth T. Ramos",
    ownership_type: "Owner",
    gender: "Female",
    birthdate: "1972-03-09",
    age: 54,
    address: "Block 4 Lot 22, St. Joseph Village 6 Phase 4",
    household_count: 5,
    contact_mobile: "0922-333-8899",
    contact_email: "dr.ramos@example.com",
    pet_count: 3,
    ga_proxy_name: "Ricardo Ramos",
    ga_proxy_relationship: "Brother",
    status: "Active",
    created_at: "2026-02-02T16:10:00Z",
    household_members: [
      { id: "hm-401", homeowner_id: "ho-0004", member_name: "Ricardo Ramos", relationship: "Brother" },
      { id: "hm-402", homeowner_id: "ho-0004", member_name: "Chloe Ramos", relationship: "Niece" },
      { id: "hm-403", homeowner_id: "ho-0004", member_name: "Elena Bautista", relationship: "Household Helper" },
      { id: "hm-404", homeowner_id: "ho-0004", member_name: "Mark Ramos", relationship: "Nephew" },
    ],
  },
  {
    id: "ho-0005",
    full_name: "Arnold P. Bautista",
    ownership_type: "Renter",
    gender: "Male",
    birthdate: "1992-06-30",
    age: 34,
    address: "Block 15 Lot 11, St. Joseph Village 6 Phase 4",
    household_count: 1,
    contact_mobile: "0919-444-7722",
    contact_email: "arnold.bautista@example.com",
    pet_count: 0,
    ga_proxy_name: "",
    ga_proxy_relationship: "",
    status: "Inactive",
    created_at: "2026-02-14T13:00:00Z",
    household_members: [],
  },
  {
    id: "ho-0006",
    full_name: "Guillermo 'Jun' F. Morales",
    ownership_type: "Owner",
    gender: "Male",
    birthdate: "1960-09-18",
    age: 65,
    address: "Block 3 Lot 5, St. Joseph Village 6 Phase 4",
    household_count: 3,
    contact_mobile: "0917-888-9900",
    contact_email: "jun.morales@example.com",
    pet_count: 2,
    ga_proxy_name: "Luzviminda Morales",
    ga_proxy_relationship: "Spouse",
    status: "Active",
    created_at: "2026-02-20T10:00:00Z",
    household_members: [
      { id: "hm-601", homeowner_id: "ho-0006", member_name: "Luzviminda Morales", relationship: "Spouse" },
      { id: "hm-602", homeowner_id: "ho-0006", member_name: "Jerome Morales", relationship: "Son" },
    ],
  },
];

export const MOCK_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: "act-01",
    user_name: "Atty. Renato Ramos",
    action: "CREATED_HOMEOWNER",
    details: { name: "Eduardo M. Santos", address: "Block 12 Lot 8" },
    created_at: "2026-01-10T14:20:00Z",
  },
  {
    id: "act-02",
    user_name: "Engr. Marilou Cruz",
    action: "CREATED_HOMEOWNER",
    details: { name: "Corazon V. Reyes", address: "Block 7 Lot 15" },
    created_at: "2026-01-12T09:15:00Z",
  },
  {
    id: "act-03",
    user_name: "Carla Mae Dizon",
    action: "CREATED_HOMEOWNER",
    details: { name: "Rafael James D. De Guzman", address: "Block 19 Lot 4" },
    created_at: "2026-01-20T11:45:00Z",
  },
  {
    id: "act-04",
    user_name: "Atty. Renato Ramos",
    action: "UPDATED_USER_PERMISSIONS",
    details: { target_user: "Carla Mae Dizon", changes: "Granted can_create_homeowner" },
    created_at: "2026-02-05T08:30:00Z",
  },
  {
    id: "act-05",
    user_name: "Engr. Marilou Cruz",
    action: "EXPORTED_EXCEL",
    details: { count: 6, format: ".xlsx" },
    created_at: "2026-02-28T15:00:00Z",
  },
];
